public enum BallMoviments
{
    STRAIGHTRIGHT,
    STRAIGHTLEFT,
    UP30RIGHT,
    UP45RIGHT,
    UP60RIGHT,
    UP30LEFT,
    UP45LEFT,
    UP60LEFT,
    DOWN30RIGHT,
    DOWN45RIGHT,
    DOWN60RIGHT,
    DOWN30LEFT,
    DOWN45LEFT,
    DOWN60LEFT
}
